import type { Job, RunRecord, RunState } from '../api'

/** Stand-in jobs for preview mode, so "Run my first search" has something to
 * show without a real Groq key or a real search. Covers every tier, a couple
 * of buckets, and every status tab, so the whole Dashboard UI is reviewable. */
export const PREVIEW_JOBS: Job[] = [
  {
    id: 'preview-1',
    run_id: 9001,
    found_at: new Date(Date.now() - 2 * 3600_000).toISOString(),
    source: "Employer's site",
    title: 'Senior QA Engineer',
    company: 'Acme Corp',
    location: 'Remote',
    url: 'https://example.com/jobs/senior-qa-engineer',
    description:
      'We are looking for a Senior QA Engineer to own quality across our platform. You will build and maintain automated test suites, work closely with engineering on release readiness, and mentor junior testers. Strong experience with Selenium and CI pipelines required.',
    age_days: 1,
    direct: true,
    bucket: 1,
    bucket_label: 'Remote, worldwide',
    score: 88,
    tier: 'apply',
    reason: 'Strong skills overlap, right level, and fully remote with no location restriction.',
    visa_sponsorship: 'unclear',
    remote_type: 'remote_worldwide',
    years_required: 4,
    salary: { salary_min: 70000, salary_max: 90000, salary_currency: 'USD', salary_period: 'year' },
    salary_below_minimum: false,
    matched_skills: ['Selenium', 'Python', 'CI/CD'],
    missing_skills: ['Cypress'],
    resume_tips: ['Add "Cypress" if you have used it, since the posting names it directly.'],
    status: 'new',
  },
  {
    id: 'preview-2',
    run_id: 9001,
    found_at: new Date(Date.now() - 5 * 3600_000).toISOString(),
    source: 'Remotive',
    title: 'Test Automation Engineer',
    company: 'Umbrella Systems',
    location: 'Dubai, UAE',
    url: 'https://example.com/jobs/test-automation-engineer',
    description:
      'Join our QA team to design and implement automated test frameworks for our fintech product. You will work with Playwright and Python, and collaborate with a distributed engineering team.',
    age_days: 0,
    direct: false,
    bucket: 0,
    bucket_label: 'In your target countries',
    score: 91,
    tier: 'apply',
    reason: 'Right role, right level, and based in one of your target countries.',
    visa_sponsorship: 'yes',
    remote_type: 'onsite',
    years_required: 3,
    salary: { salary_min: 15000, salary_max: 20000, salary_currency: 'AED', salary_period: 'month' },
    salary_below_minimum: false,
    matched_skills: ['Python', 'Test Automation'],
    missing_skills: ['Playwright'],
    resume_tips: ['List Playwright explicitly if you have used it — it is the posting’s main tool.'],
    status: 'new',
  },
  {
    id: 'preview-3',
    run_id: 9001,
    found_at: new Date(Date.now() - 8 * 3600_000).toISOString(),
    source: 'JSearch',
    title: 'QA Automation Lead',
    company: 'Globex',
    location: 'Remote (EU only)',
    url: 'https://example.com/jobs/qa-automation-lead',
    description:
      'Lead our QA automation efforts across three product teams. You will set testing strategy, review test plans, and pair with engineers on tricky bugs. Remote within the EU.',
    age_days: 3,
    direct: false,
    bucket: 1,
    bucket_label: 'Remote, worldwide',
    score: 74,
    tier: 'strong',
    reason: 'Good role in range, but the remote arrangement is limited to the EU.',
    visa_sponsorship: 'no',
    remote_type: 'remote_regional',
    years_required: 6,
    salary: { salary_min: null, salary_max: null, salary_currency: '', salary_period: '' },
    salary_below_minimum: false,
    matched_skills: ['Selenium', 'Team Leadership'],
    missing_skills: ['Kubernetes'],
    resume_tips: ['Quantify a leadership result, e.g. team size or release cadence improved.'],
    status: 'new',
  },
  {
    id: 'preview-4',
    run_id: 9001,
    found_at: new Date(Date.now() - 26 * 3600_000).toISOString(),
    source: 'Adzuna',
    title: 'Manual QA Tester',
    company: 'Initech',
    location: 'Austin, TX',
    url: 'https://example.com/jobs/manual-qa-tester',
    description:
      'Entry to mid-level QA role testing our internal tools. Some exposure to automation is a plus but not required. Great place to grow into a full QA engineering role.',
    age_days: 2,
    direct: false,
    bucket: 2,
    bucket_label: 'In your home country',
    score: 58,
    tier: 'maybe',
    reason: 'Relevant, but a step down in scope from your recent roles.',
    visa_sponsorship: 'unclear',
    remote_type: 'onsite',
    years_required: 1,
    salary: { salary_min: 45000, salary_max: 55000, salary_currency: 'USD', salary_period: 'year' },
    salary_below_minimum: true,
    matched_skills: ['Manual Testing'],
    missing_skills: [],
    resume_tips: [],
    status: 'new',
  },
  {
    id: 'preview-5',
    run_id: 9001,
    found_at: new Date(Date.now() - 30 * 3600_000).toISOString(),
    source: "Employer's site",
    title: 'SDET',
    company: 'Stark Industries',
    location: 'Remote',
    url: 'https://example.com/jobs/sdet',
    description:
      'Software Development Engineer in Test role building tooling that the whole engineering org relies on. Heavy focus on API testing and internal libraries.',
    age_days: 4,
    direct: true,
    bucket: 1,
    bucket_label: 'Remote, worldwide',
    score: 69,
    tier: 'strong',
    reason: 'Solid overlap on API testing, a slight stretch on internal tooling experience.',
    visa_sponsorship: 'unclear',
    remote_type: 'remote_worldwide',
    years_required: 3,
    salary: { salary_min: null, salary_max: null, salary_currency: '', salary_period: '' },
    salary_below_minimum: false,
    matched_skills: ['API Testing', 'Python'],
    missing_skills: ['Go'],
    resume_tips: ['Mention any internal-tooling or developer-experience work, even small.'],
    status: 'saved',
  },
  {
    id: 'preview-6',
    run_id: 9001,
    found_at: new Date(Date.now() - 50 * 3600_000).toISOString(),
    source: 'Company career page',
    title: 'QA Lead',
    company: 'Wayne Enterprises',
    location: 'Remote',
    url: 'https://example.com/jobs/qa-lead',
    description:
      'Own quality strategy for our consumer app. You will manage two QA engineers and work directly with the VP of Engineering on release quality.',
    age_days: 6,
    direct: true,
    bucket: 1,
    bucket_label: 'Remote, worldwide',
    score: 82,
    tier: 'apply',
    reason: 'Strong fit on both leadership scope and technical skills.',
    visa_sponsorship: 'unclear',
    remote_type: 'remote_worldwide',
    years_required: 5,
    salary: { salary_min: 80000, salary_max: 100000, salary_currency: 'USD', salary_period: 'year' },
    salary_below_minimum: false,
    matched_skills: ['Team Leadership', 'Test Strategy'],
    missing_skills: [],
    resume_tips: [],
    status: 'applied',
  },
  {
    id: 'preview-7',
    run_id: 9001,
    found_at: new Date(Date.now() - 70 * 3600_000).toISOString(),
    source: 'Remotive',
    title: 'Junior QA Tester',
    company: 'Wonka Co',
    location: 'Onsite, London',
    url: 'https://example.com/jobs/junior-qa-tester',
    description: 'Entry-level QA role, mostly manual regression testing on our confectionery ordering platform.',
    age_days: 9,
    direct: false,
    bucket: 3,
    bucket_label: 'Other countries',
    score: 41,
    tier: 'maybe',
    reason: 'Junior scope and onsite outside your target countries.',
    visa_sponsorship: 'no',
    remote_type: 'onsite',
    years_required: 0,
    salary: { salary_min: null, salary_max: null, salary_currency: '', salary_period: '' },
    salary_below_minimum: false,
    matched_skills: [],
    missing_skills: ['Test Case Design'],
    resume_tips: [],
    status: 'hidden',
  },
]

export const PREVIEW_RUN_STATE: RunState = {
  running: false,
  run_id: 9001,
  phase: 'done',
  message: '5 jobs worth a look',
  sources_done: 4,
  sources_total: 4,
  found: 42,
  to_score: 30,
  scored: 30,
  matches: 5,
  log: [],
}

export const PREVIEW_LAST_RUN: RunRecord = {
  id: 9001,
  started_at: new Date(Date.now() - 2 * 3600_000).toISOString(),
  finished_at: new Date(Date.now() - 2 * 3600_000 + 4 * 60_000).toISOString(),
  trigger: 'manual',
  status: 'done',
  stats: {
    found: 42,
    new: 42,
    fresh: 38,
    passed_rules: 30,
    scored: 30,
    matches: 5,
    per_source: { "Employer's site": 12, Remotive: 15, JSearch: 8, Adzuna: 7 },
    rejected: { 'title contains "intern"': 3, 'outside your countries': 5 },
  },
  error: null,
}
